platform: linux
image_resource:
  type: registry-image
inputs:
  - name: gpdb_src
outputs:
  - name: gpdb_artifacts
run:
  path: gpdb_src/concourse/scripts/compile_gpdb.bash
params:
  BLD_TARGETS:
  OUTPUT_ARTIFACT_DIR: gpdb_artifacts
  CONFIGURE_FLAGS:
  RC_BUILD_TYPE_GCS:
  SKIP_UNITTESTS:
