platform: linux
image_resource:
  type: registry-image
inputs:
  - name: gpdb_src
  - name: abi_test_src
  - name: bin_gpdb
  - name: bin_gpdb_clients
params:
  TEST_OS: ""
  CONFIGURE_FLAGS: ""
  WITH_MIRRORS:
run:
  path: gpdb_src/concourse/scripts/scram-sha-256_abi_test.bash
