## ======================================================================
## resources
## ======================================================================

resource_types:
  - name: gcs
    type: docker-image
    source:
        repository: frodenas/gcs-resource

resources:
- name: pgbouncer_src
  type: git
  source:
    access_token: {{git-access-token}}
    branch: {{git-branch}}
    repo: greenplum-db/pgbouncer
    uri: https://github.com/greenplum-db/pgbouncer.git

- name: gpdb7-centos7-build
  type: registry-image
  source:
    repository: pivotaldata/gpdb7-centos7-build

- name: gpdb7-centos7-test
  type: docker-image
  source:
    repository: pivotaldata/gpdb7-centos7-test
    tag: latest

- name: gpdb7-ubuntu18.04-build
  type: registry-image
  source:
    repository: pivotaldata/gpdb7-ubuntu18.04-build
    tag: latest

- name: gpdb7-ubuntu18.04-test
  type: registry-image
  source:
    repository: pivotaldata/gpdb7-ubuntu18.04-test
    tag: latest

- name: gpdb7_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/gpdb.git
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: bin_gpdb7_centos7
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: server/published/master/server-rc-(.*)-rhel7_x86_64.tar.gz

- name: bin_gpdb7_ubuntu18.04
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: server/published/master/server-rc-(.*)-ubuntu18.04_x86_64.tar.gz

- name: bin_pgbouncer_centos7
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{pgbouncer-bucket}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: intermediates/components_pgbouncer/centos7/bin_pgbouncer.tar.gz

- name: bin_pgbouncer_ubuntu18.04
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{pgbouncer-bucket}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: intermediates/components_pgbouncer/ubuntu18.04/bin_pgbouncer.tar.gz
jobs:
- name: build_pgbouncer_centos7
  plan:
  - in_parallel:
      steps:
      - get: pgbouncer_src
        trigger: true
      - get: gpdb7-centos7-build
  - task: build_pgbouncer
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      outputs:
      - name: bin_pgbouncer
      run:
        path: pgbouncer_src/concourse/scripts/build.bash
    image: gpdb7-centos7-build
    timeout: 30m
  - put: bin_pgbouncer
    resource: bin_pgbouncer_centos7
    params:
      file: bin_pgbouncer/bin_pgbouncer.tar.gz
- name: test_pgbouncer_gpdb7_centos7
  plan:
  - in_parallel:
      steps:
      - get: pgbouncer_src
      - get: gpdb7-centos7-test
      - get: gpdb7_src
      - get: bin_gpdb
        resource: bin_gpdb7_centos7
      - get: bin_pgbouncer_centos7
        passed:
        - build_pgbouncer_centos7
        trigger: true
  - task: psql_test
    input_mapping:
      gpdb_src: gpdb7_src
      bin_pgbouncer: bin_pgbouncer_centos7
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      - name: bin_gpdb
      - name: bin_pgbouncer
      run:
        path: pgbouncer_src/concourse/scripts/psql_test.bash
    image: gpdb7-centos7-test
    timeout: 30m

- name: build_pgbouncer_ubuntu18.04
  plan:
  - in_parallel:
      steps:
      - get: pgbouncer_src
        trigger: true
      - get: gpdb7-ubuntu18.04-build
  - task: build_pgbouncer
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      outputs:
      - name: bin_pgbouncer
      run:
        path: pgbouncer_src/concourse/scripts/build.bash
    image: gpdb7-ubuntu18.04-build
    timeout: 30m
  - put: bin_pgbouncer
    resource: bin_pgbouncer_ubuntu18.04
    params:
      file: bin_pgbouncer/bin_pgbouncer.tar.gz

- name: test_pgbouncer_gpdb7_ubuntu18.04
  plan:
  - in_parallel:
      steps:
      - get: pgbouncer_src
      - get: gpdb7-ubuntu18.04-test
      - get: gpdb7_src
      - get: bin_gpdb
        resource: bin_gpdb7_ubuntu18.04
      - get: bin_pgbouncer_ubuntu18.04
        passed:
        - build_pgbouncer_ubuntu18.04
        trigger: true
  - task: psql_test
    input_mapping:
      gpdb_src: gpdb7_src
      bin_pgbouncer: bin_pgbouncer_ubuntu18.04
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      - name: bin_gpdb
      - name: bin_pgbouncer
      run:
        path: pgbouncer_src/concourse/scripts/psql_test.bash
    image: gpdb7-ubuntu18.04-test
    timeout: 30m
